#-------------------------------------------------------------
#- Docker compose base definition file to run containers.
#-----------------------------------------------------------

version: '3.6'
services:
  weather-app:
    build:
      context: ${APP_CONTEXT}
      dockerfile: Dockerfile
      args:
        APP_BASE_IMAGE: ${APP_BASE_IMAGE}
        APP_ARTIFACT_ID: ${APP_ARTIFACT_ID}
        JAVA_OPTIONS: ${JAVA_OPTIONS}
    image: ${APP_IMAGE}
    ports:
      - "8080:8080"